# Generated by Django 3.1.7 on 2021-07-03 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=10)),
                ('book_id', models.CharField(max_length=100)),
                ('book_time', models.DateTimeField()),
                ('ad_name', models.CharField(max_length=100)),
                ('ad_pic', models.CharField(max_length=2083)),
                ('ad_id', models.CharField(max_length=100)),
            ],
        ),
    ]
