# Generated by Django 3.1.7 on 2021-07-03 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_booking'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advisor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad_id', models.CharField(default=None, max_length=100)),
                ('name', models.CharField(max_length=200)),
                ('photo_url', models.CharField(max_length=2083)),
            ],
        ),
    ]
