# Generated by Django 3.1.7 on 2021-07-03 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0003_advisor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='book_time',
            field=models.CharField(max_length=100),
        ),
    ]
